"use client";
import{FormEvent,useEffect,useState}from"react";
import{getSupabaseBrowser}from"../../lib/supabase-client";
type Post={id:string;body:string;createdAt:number;author:string;authorEmail?:string};
export default function Community(){
  const[posts,setPosts]=useState<Post[]>([]),[body,setBody]=useState(""),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
  const supabase=getSupabaseBrowser();
  async function token(){return(await supabase?.auth.getSession())?.data.session?.access_token||""}
  useEffect(()=>{if(!supabase)return;(async()=>{const t=await token();if(!t){location.href="/login?next=/community";return}const response=await fetch("/api/community",{headers:{authorization:`Bearer ${t}`}});if(response.ok)setPosts(await response.json());setLoading(false)})()},[supabase]);
  async function publish(event:FormEvent){event.preventDefault();if(!body.trim())return;setMessage("Publishing…");const response=await fetch("/api/community",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${await token()}`},body:JSON.stringify({body})});if(response.ok){const post=await response.json();setPosts([post,...posts]);setBody("");setMessage("Posted to the community.")}else setMessage("Your post could not be published.")}
  return <main className="community-page"><header><a className="system-brand" href="/">✦ NORTHSTARLABS</a><nav><a href="/learn">My learning</a><a href="/courses">Courses</a><a href="/dashboard">Creator workspace</a></nav></header><section className="community-hero"><div><p className="sys-kicker">NORTHSTAR CIRCLE</p><h1>Learn together.<br/>Grow together.</h1><p>Ask questions, share useful discoveries, and celebrate progress with the NorthstarLabs community.</p></div><aside><strong>{posts.length}</strong><span>recent conversations</span></aside></section><section className="community-stream"><form className="panel community-composer" onSubmit={publish}><label htmlFor="community-post">Share something with the circle</label><textarea id="community-post" maxLength={1500} value={body} onChange={e=>setBody(e.target.value)} placeholder="Ask a question, share a win, or offer an insight…"/><div><small>{body.length}/1500</small><button className="sys-primary">Publish post</button></div>{message&&<p className="form-message">{message}</p>}</form><div className="feed"><h2>Community feed</h2>{loading?<p>Loading conversations…</p>:posts.length?posts.map(post=><article className="panel community-post" key={post.id}><span>{post.author.slice(0,2).toUpperCase()}</span><div><header><b>{post.author}</b><small>{new Date(post.createdAt).toLocaleDateString("en-ZA",{day:"numeric",month:"short",year:"numeric"})}</small></header><p>{post.body}</p></div></article>):<article className="panel empty-dashboard"><h2>Start the first conversation</h2><p>Welcome the community, ask a question, or share what you are building.</p></article>}</div></section></main>
}
