INSERT OR REPLACE INTO `media_assets` (`id`,`school_id`,`owner_id`,`key`,`filename`,`content_type`,`size_bytes`,`kind`,`alt_text`,`created_at`,`updated_at`) SELECT 'cmf-module-1-2-exchange-video',c.`school_id`,c.`owner_id`,'static:/media/faculty/module-1-2-obligations-to-coins.mp4','module-1-2-obligations-to-coins.mp4','video/mp4',1675887,'video','Narrated visual lesson for Module 1.2 of Crypto Mastery.',1785394800000,1785394800000 FROM `courses` c WHERE c.`id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
UPDATE `lessons` SET `lesson_type`='video',`primary_asset_id`='cmf-module-1-2-exchange-video',`required_watch_percent`=75,`transcript`='The history of money is not a straight line from barter to coins. Communities have long combined direct exchange, reciprocal obligation and credit. A neighbour might supply food today because the relationship carries an expectation of future return. A merchant might record a debt and settle it later. Barter mattered, especially when people lacked a shared unit, but it was one tool among several.

Direct exchange becomes difficult when each party must want the other''s exact offer at the same time. Economists call this the double coincidence of wants. Goods may also spoil, resist division or be difficult to compare. Societies responded by using things that many people would accept: grain, shells, salt, livestock and metals. Commodity money had value as a product as well as a medium of exchange.

Commodity systems still needed quality checks, weighing and transport. Standardised coins changed the operating model. A recognised issuer marked a piece of metal with a weight and denomination. The object became easier to identify, divide and count. The stamp reduced repeated verification, but it introduced a governance question: could the issuer be trusted to maintain the standard?

This is the pattern to notice. Monetary innovations do not simply replace an object. They rearrange coordination, verification and trust. Use the timeline lab below to identify the problem each system solved and the dependency it added.',`updated_at`=1785394800000 WHERE `id`='cmf-module-1-2-lesson-01' AND `course_id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
INSERT OR REPLACE INTO `media_assets` (`id`,`school_id`,`owner_id`,`key`,`filename`,`content_type`,`size_bytes`,`kind`,`alt_text`,`created_at`,`updated_at`) SELECT 'cmf-module-1-2-claims-video',c.`school_id`,c.`owner_id`,'static:/media/faculty/module-1-2-claims-ledgers-fiat.mp4','module-1-2-claims-ledgers-fiat.mp4','video/mp4',1587701,'video','Narrated visual lesson for Module 1.2 of Crypto Mastery.',1785394800000,1785394800000 FROM `courses` c WHERE c.`id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
UPDATE `lessons` SET `lesson_type`='video',`primary_asset_id`='cmf-module-1-2-claims-video',`required_watch_percent`=75,`transcript`='Paper money began partly as a safer way to move claims. Instead of carrying heavy metal, a holder could carry a receipt for metal stored elsewhere. When other people accepted the receipt directly, the claim itself began to circulate. This is representative money: the note represents something redeemable under the system''s rules.

Banking moved money further toward ledger entries. Deposits are recorded claims on a bank. Payments update records across institutions, and bank lending can create new deposit balances. The majority of everyday money can therefore be digital without being a cryptocurrency.

Modern fiat currency is not normally redeemable for a fixed quantity of gold. It operates through a wider institutional system: the issuing state, central bank, legal rules, taxation, monetary policy, productive capacity and public acceptance. Calling fiat money unbacked misses those dependencies. It is not commodity-backed, but it is institutionally supported.

Every stage changes the trust boundary. A metal holder may verify weight and purity. A note holder relies on redemption. A bank customer relies on the bank and payment system. A fiat user relies on monetary governance and broad acceptance. In the activity below, locate the claim, the ledger and the failure mode instead of judging a system only by what its money looks like.',`updated_at`=1785394800000 WHERE `id`='cmf-module-1-2-lesson-02' AND `course_id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
INSERT OR REPLACE INTO `media_assets` (`id`,`school_id`,`owner_id`,`key`,`filename`,`content_type`,`size_bytes`,`kind`,`alt_text`,`created_at`,`updated_at`) SELECT 'cmf-module-1-2-change-video',c.`school_id`,c.`owner_id`,'static:/media/faculty/module-1-2-why-money-changes.mp4','module-1-2-why-money-changes.mp4','video/mp4',1789930,'video','Narrated visual lesson for Module 1.2 of Crypto Mastery.',1785394800000,1785394800000 FROM `courses` c WHERE c.`id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
UPDATE `lessons` SET `lesson_type`='video',`primary_asset_id`='cmf-module-1-2-change-video',`required_watch_percent`=75,`transcript`='Money changes when a new arrangement solves a useful coordination problem. Coins improved standardisation and portability. Paper reduced the burden of moving metal. Bank ledgers made credit and remote transfer scalable. Electronic payments improved speed and convenience.

Each improvement also created dependencies and risks. Coins could be debased. Paper claims could be over-issued or refused. Banks could fail. Digital payment accounts could be hacked, frozen or excluded. Progress changes risk; it does not erase it.

Cryptocurrency belongs in this continuing history. Bitcoin combined digital signatures, peer-to-peer networking, proof of work and economic incentives so that independent participants could agree on a transaction history without one account provider maintaining the authoritative ledger. The important innovation was not simply digital money. Bank balances were already digital. The change was the ledger and control model.

That does not prove that cryptocurrency will replace cash, bank deposits or state currency. Monetary systems commonly coexist because they serve different needs. A useful comparison asks what problem is being solved, what new dependency is introduced, who can change the rules, how disputes are handled and what happens under stress.

Use the innovation scorecard below to compare systems without slogans. A faster payment is not automatically safer. A decentralised ledger is not automatically suitable for every transaction. The goal is to understand the trade, not choose a winner in advance.',`updated_at`=1785394800000 WHERE `id`='cmf-module-1-2-lesson-03' AND `course_id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
INSERT OR REPLACE INTO `media_assets` (`id`,`school_id`,`owner_id`,`key`,`filename`,`content_type`,`size_bytes`,`kind`,`alt_text`,`created_at`,`updated_at`) SELECT 'cmf-module-1-2-field-lab',c.`school_id`,c.`owner_id`,'static:/media/course-resources/module-1-2-evolution-of-money-field-lab.pdf','Module 1.2 Evolution of Money Field Lab.pdf','application/pdf',8505,'document','Applied comparison lab for monetary evolution, trust and system trade-offs.',1785394800000,1785394800000 FROM `courses` c WHERE c.`id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
INSERT OR REPLACE INTO `lesson_resources` (`id`,`lesson_id`,`asset_id`,`title`,`position`) VALUES ('cmf-module-1-2-field-lab-link','cmf-module-1-2-lesson-03','cmf-module-1-2-field-lab','Evolution of Money Field Lab',1);
