INSERT OR REPLACE INTO `media_assets` (`id`,`school_id`,`owner_id`,`key`,`filename`,`content_type`,`size_bytes`,`kind`,`alt_text`,`created_at`,`updated_at`) SELECT 'cmf-module-1-13-recovery-chain-video',c.`school_id`,c.`owner_id`,'static:/media/faculty/module-1-13-recovery-chain.mp4','module-1-13-recovery-chain.mp4','video/mp4',1192600,'video','Neural-narrated visual lesson for cmf-module-1-13-lesson-01.',1784952000000,1784952000000 FROM `courses` c WHERE c.`id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
UPDATE `lessons` SET `lesson_type`='video',`primary_asset_id`='cmf-module-1-13-recovery-chain-video',`required_watch_percent`=75,`transcript`='A recovery phrase is portable authority, not a password hint. It can recreate the wallet keys associated with a compatible wallet, which is why the phrase must be treated like the highest value secret in the system. The order of the words matters, the spelling matters and the optional passphrase matters. If any part is wrong, the restored wallet can be different or inaccessible. The local wallet password or PIN is not the same thing. A password may protect the interface on one device, but the recovery phrase can recreate the wallet elsewhere. That is why cloud screenshots, photos and chat messages are risky backups even when they feel convenient. A good recovery design balances confidentiality and recoverability. The learner should keep durable copies in separated locations, test the process with disposable credentials and know what to do if the phrase is exposed. If compromise is suspected, changing the app password is not enough. The safe response is to create a new secure wallet and move value under new keys after verifying the plan.',`updated_at`=1784952000000 WHERE `id`='cmf-module-1-13-lesson-01' AND `course_id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
INSERT OR REPLACE INTO `media_assets` (`id`,`school_id`,`owner_id`,`key`,`filename`,`content_type`,`size_bytes`,`kind`,`alt_text`,`created_at`,`updated_at`) SELECT 'cmf-module-1-14-exchange-ledger-video',c.`school_id`,c.`owner_id`,'static:/media/faculty/module-1-14-exchange-ledger.mp4','module-1-14-exchange-ledger.mp4','video/mp4',1227716,'video','Neural-narrated visual lesson for cmf-module-1-14-lesson-01.',1784952000000,1784952000000 FROM `courses` c WHERE c.`id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
UPDATE `lessons` SET `lesson_type`='video',`primary_asset_id`='cmf-module-1-14-exchange-ledger-video',`required_watch_percent`=75,`transcript`='A centralised exchange is a service provider, not the blockchain itself. The clean way to understand it is to follow the money and the records separately. A bank deposit enters the exchange through ordinary payment rails. The platform then updates an internal customer ledger. A trade usually changes those internal records before anything moves on chain. Only when a withdrawal is made does the platform broadcast a blockchain transaction. That distinction matters because the balance visible in the account depends on the exchange''s database and controls. It is not the same thing as a balance on the public network. This is why operational risk, custody risk and solvency risk matter so much. A learner must ask who holds the keys, who can freeze the account, what the fee structure is, what the withdrawal rules are and how the platform is regulated. The platform can make buying easy, but it also creates trust dependency. The right habit is to treat the exchange like a service you use, not like proof that you own the asset until you have withdrawn it to your own wallet.',`updated_at`=1784952000000 WHERE `id`='cmf-module-1-14-lesson-01' AND `course_id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
INSERT OR REPLACE INTO `media_assets` (`id`,`school_id`,`owner_id`,`key`,`filename`,`content_type`,`size_bytes`,`kind`,`alt_text`,`created_at`,`updated_at`) SELECT 'cmf-module-1-15-dex-risk-stack-video',c.`school_id`,c.`owner_id`,'static:/media/faculty/module-1-15-dex-risk-stack.mp4','module-1-15-dex-risk-stack.mp4','video/mp4',1272942,'video','Neural-narrated visual lesson for cmf-module-1-15-lesson-01.',1784952000000,1784952000000 FROM `courses` c WHERE c.`id`='cognizen-crypto-mastery-foundations-production';
--> statement-breakpoint
UPDATE `lessons` SET `lesson_type`='video',`primary_asset_id`='cmf-module-1-15-dex-risk-stack-video',`required_watch_percent`=75,`transcript`='A decentralised exchange looks different because the trade is coordinated by smart contracts rather than a traditional custodial platform, but the learner still needs to inspect the risk stack. A DEX can reduce some custody dependence, yet it introduces contract risk, interface risk, token-approval risk, oracle risk, liquidity risk and bridge risk. A wallet approval is especially important because the user may authorise a contract to move tokens later without realising how broad the permission is. Liquidity pools also create a different execution model from an order book. Large swaps can move the price against the trader, creating slippage and price impact. That is why a low-fee swap is not automatically a safer swap. The learner should verify the contract address, inspect the permission being requested, understand the network and size the transaction against available liquidity. The lesson is not that DEXs are bad. The lesson is that decentralised is a description of architecture, not a guarantee of safety, simplicity or fairness. Good judgment still matters.',`updated_at`=1784952000000 WHERE `id`='cmf-module-1-15-lesson-01' AND `course_id`='cognizen-crypto-mastery-foundations-production';
