"use client";
import{useEffect,useState}from"react";
import{getSupabaseBrowser}from"../../lib/supabase-client";
type Enrolment={courseId:string;title:string;description:string;progress:number};
export default function LearnerHome(){
  const[items,setItems]=useState<Enrolment[]>([]),[loading,setLoading]=useState(true);
  const supabase=getSupabaseBrowser();
  useEffect(()=>{if(!supabase)return;(async()=>{const session=(await supabase.auth.getSession()).data.session;if(!session){location.href="/login?next=/learn";return}const response=await fetch("/api/enrollments",{headers:{authorization:`Bearer ${session.access_token}`}});if(response.ok)setItems(await response.json());setLoading(false)})()},[supabase]);
  async function signOut(){await supabase?.auth.signOut();location.href="/"}
  return <main className="learner-home"><header><a className="system-brand" href="/">✦ NORTHSTARLABS</a><nav><a href="/courses">Explore courses</a><a href="/community">Community</a><button onClick={signOut}>Sign out</button></nav></header><section className="learner-welcome"><p className="sys-kicker">MY LEARNING</p><h1>Keep moving forward.</h1><p>Your courses, progress, and next lessons live here.</p></section><section className="learner-library"><div className="library-heading"><div><h2>Your courses</h2><p>Continue exactly where you left off.</p></div><a className="builder-preview" href="/courses">Browse all courses →</a></div>{loading?<p>Loading your learning…</p>:items.length?<div className="learning-grid">{items.map(item=><article className="panel" key={item.courseId}><span className="course-art">{item.title.slice(0,2).toUpperCase()}</span><p className="sys-kicker">IN PROGRESS</p><h3>{item.title}</h3><p>{item.description||"Continue your next lesson and put your learning into practice."}</p><div className="progress-line"><i><b style={{width:`${item.progress||0}%`}}/></i><span>{item.progress||0}%</span></div><a className="sys-primary" href={`/learn/${item.courseId}`}>Continue learning →</a></article>)}</div>:<article className="panel empty-dashboard"><h2>Your learning space is ready</h2><p>Enrol in a course and it will appear here automatically.</p><a className="sys-primary" href="/courses">Explore courses →</a></article>}</section></main>
}
