$ErrorActionPreference = "Stop"
$project = Split-Path -Parent $PSScriptRoot
$output = Join-Path $project "public\media\faculty"
New-Item -ItemType Directory -Force -Path $output | Out-Null
$ffmpeg = node -e "process.stdout.write(require('ffmpeg-static'))"
if (-not (Test-Path -LiteralPath $ffmpeg)) { throw "The bundled video encoder is unavailable." }

$items = @(
  @{ File="module-1-3-digital-cash-problem"; Kicker="MODULE 1.3  |  THE DESIGN PROBLEM"; Title="ONE INPUT. TWO CONFLICTING SPENDS."; Line1="AUTHORISATION"; Line2="ORDERING"; Line3="ACCEPTED HISTORY"; Close="CONSENSUS SOLVES A LEDGER PROBLEM"; Prompt="NOT EVERY HUMAN TRUST PROBLEM"; Script="Before Bitcoin, digital payment systems could already move value quickly. The difficult question was narrower: how could a native digital unit be transferred without a central operator preventing it from being spent twice? Digital information is easy to copy. If Alice sends the same signed input to Bob and Carol, signatures can prove that Alice authorised both messages. A signature alone cannot tell the network which conflicting spend should count. The system also needs common validity rules and an accepted ordering of events. Traditional payment systems solve this with an authoritative ledger. A bank or payment operator checks the account, records one transaction, rejects the conflict and handles disputes. That model can be efficient, but the operator becomes the trusted coordinator. Bitcoin proposed a different coordination structure. Transactions are broadcast to a peer-to-peer network. Nodes independently test them against shared rules. Miners group valid transactions into blocks and perform proof of work. Hash links connect each accepted block to the history before it. The network follows the valid chain with the most accumulated work, making large-scale history replacement costly. This is not magic and it does not remove every intermediary. Wallets, exchanges, internet access and custody services can still introduce trust and risk. The protocol addresses agreement over ledger history. Use the conflict lab below to separate that achievement from claims it never made." },
  @{ File="module-1-3-technical-ancestry"; Kicker="MODULE 1.3  |  TECHNICAL ANCESTRY"; Title="THE BREAKTHROUGH WAS THE COMBINATION"; Line1="SIGNATURES + HASHES"; Line2="PROOF OF WORK + NETWORK"; Line3="RULES + INCENTIVES"; Close="A SYSTEM, NOT ONE MAGIC INGREDIENT"; Prompt="MAP EACH PART TO ITS JOB"; Script="Bitcoin did not appear without ancestors. Its design combined decades of research into cryptography, distributed systems and digital money. Public-key signatures provided a way to authorise transfers without revealing the private signing key. Cryptographic hashes made a compact fingerprint of data, so a changed record produced a changed result. Merkle trees let many transactions be summarised and checked efficiently. Timestamping research showed how records could be chained so that later evidence strengthened earlier evidence. Hashcash used computational puzzles to make abusive activity costly. Proposals such as b-money and bit gold explored scarce digital objects, distributed records and incentive structures. Peer-to-peer networks demonstrated how participants could communicate without one central server. Bitcoin's breakthrough was the system-level combination. Proof of work did more than rate-limit messages: it helped order blocks and made alternative histories expensive. The block reward and transaction fees gave participants an economic reason to contribute resources. Full nodes applied the rules independently, so producing work did not give a miner permission to create invalid money. Do not reduce this ancestry to a single inventor or ingredient. The learning value lies in seeing how authorisation, integrity, ordering, incentives and verification reinforce one another. In the systems map below, match each component to its direct job, then explain why no component is sufficient on its own." },
  @{ File="module-1-3-white-paper-claims"; Kicker="MODULE 1.3  |  PRIMARY-SOURCE READING"; Title="A DESIGN DOCUMENT. NOT A PRICE PROPHECY."; Line1="CLAIM"; Line2="MECHANISM + ASSUMPTION"; Line3="EVIDENCE STILL NEEDED"; Close="READ AT THE LEVEL OF THE CLAIM"; Prompt="SEPARATE PROTOCOL FROM NARRATIVE"; Script="The Bitcoin white paper is a design document, not an investment prospectus. Read its claims at the level they are made. The stated goal is peer-to-peer electronic cash: online payments sent directly without relying on a financial institution to order every transaction. The paper outlines a chain of digital signatures, public transaction broadcast, timestamped blocks, proof of work, node acceptance rules and incentives. Its security reasoning is conditional. It assumes honest participants control more computing power than a coordinated attacker, and it discusses probabilities rather than absolute impossibility. Later implementations, governance practices and market infrastructure also extend beyond the paper's nine-page design. The document does not guarantee price appreciation. It does not prove that every exchange, wallet or token is safe. It does not recover a lost private key, eliminate software defects or settle every legal question. Limited supply is a protocol property; future value still depends on demand, use, regulation, competition and human behaviour. A disciplined reader separates four layers: what the primary source states, what mechanism supports the claim, what assumption limits it, and what later evidence is required. Use the claim audit below before repeating any story about Bitcoin. The objective is not belief or disbelief. It is a conclusion whose boundaries another person can inspect." }
)

$font = "C\:/Windows/Fonts/arial.ttf"; $bold = "C\:/Windows/Fonts/arialbd.ttf"
$python = "C:\Users\Hugo\.cache\codex-runtimes\codex-primary-runtime\dependencies\python\python.exe"
foreach ($item in $items) {
  $wav = Join-Path $output "$($item.File).wav"; $mp4 = Join-Path $output "$($item.File).mp4"
  & $python (Join-Path $PSScriptRoot "generate-neural-voice.py") --text $item.Script --output $wav --voice bm_george --speed 0.98
  if ($LASTEXITCODE -ne 0) { throw "Neural narration failed for $($item.File)." }
  $filter = "drawbox=x=0:y=0:w=1280:h=720:color=0x11131f:t=fill," +
    "drawbox=x=56:y=54:w=1168:h=612:color=0x1d2033:t=fill," +
    "drawbox=x=56:y=54:w=1168:h=8:color=0xd9ff65:t=fill," +
    "drawtext=fontfile='$bold':text='$($item.Kicker)':fontcolor=0xffbd8a:fontsize=22:x=96:y=100," +
    "drawtext=fontfile='$bold':text='$($item.Title)':fontcolor=white:fontsize=40:x=96:y=230:enable='between(t,0,24)'," +
    "drawtext=fontfile='$font':text='Follow the problem. Test the mechanism. Bound the claim.':fontcolor=0xc9ccda:fontsize=28:x=96:y=327:enable='between(t,0,24)'," +
    "drawtext=fontfile='$bold':text='$($item.Line1)':fontcolor=white:fontsize=39:x=96:y=194:enable='between(t,24,66)'," +
    "drawtext=fontfile='$bold':text='$($item.Line2)':fontcolor=0x7ca0ff:fontsize=39:x=96:y=280:enable='between(t,24,66)'," +
    "drawtext=fontfile='$bold':text='$($item.Line3)':fontcolor=0xd9ff65:fontsize=39:x=96:y=366:enable='between(t,24,66)'," +
    "drawtext=fontfile='$bold':text='$($item.Close)':fontcolor=white:fontsize=33:x=96:y=252:enable='gte(t,66)'," +
    "drawtext=fontfile='$font':text='$($item.Prompt)':fontcolor=0xffbd8a:fontsize=27:x=96:y=350:enable='gte(t,66)'," +
    "drawtext=fontfile='$bold':text='COGNIZEN CONSULTING  |  NORTHSTARLABS':fontcolor=white:fontsize=20:x=96:y=610"
  & $ffmpeg -loglevel error -nostats -y -f lavfi -i "color=c=0x11131f:s=1280x720:r=30" -i $wav -vf $filter -c:v libx264 -preset medium -crf 22 -pix_fmt yuv420p -c:a aac -b:a 128k -shortest -movflags +faststart $mp4
  if ($LASTEXITCODE -ne 0) { throw "Video generation failed for $($item.File)." }
  Remove-Item -LiteralPath $wav
}
Write-Output "Created three Module 1.3 neural-narrated lessons."
